---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: postgresql
spec:
  interval: 12h
  url: oci://ghcr.io/visualon/bitnamicharts/postgresql
  ref:
    digest: sha256:4ed63727a46ff6e6e1cc48b87c75c4b2abe9e5901d38079ba22768895c00de7a
    tag: 16.7.27
