---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: postgresql
spec:
  interval: 12h
  url: oci://ghcr.io/visualon/bitnamicharts/postgresql
  ref:
    digest: sha256:c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4
    tag: 16.7.27
