---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mariadb
spec:
  interval: 12h
  url: oci://ghcr.io/visualon/bitnamicharts/mariadb
  ref:
    digest: sha256:4f069f2afb576b83d4d558460348d1777725c40dab4f4e471e0c6b465689de63
