---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: valkey
spec:
  interval: 12h
  url: oci://ghcr.io/visualon/bitnamicharts/valkey
  ref:
    digest: sha256:9a4bc30286800004817c733ba4d84eefc5bcabb515695b3d8a80d407076a557f
    # tag is for renovate and will be ignored by flux
    tag: 3.0.30