---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: valkey
spec:
  interval: 12h
  url: oci://ghcr.io/visualon/bitnamicharts/valkey
  ref:
    digest: sha256:1244a8517872368ae964edfea83368225ceaaa2d2ff84560273f96259e5e8ca6
    # tag is for renovate and will be ignored by flux
    tag: 5.4.11