---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: postgresql
spec:
  interval: 12h
  url: oci://ghcr.io/visualon/bitnamicharts/postgresql
  ref:
    digest: sha256:fac73c125728fa182d47a0b3fb5db3ee7ac35372533585dd8a4355b4797b2a16
    tag: 18.1.1
