---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ingress-nginx
spec:
  interval: 12h
  url: oci://ghcr.io/visualon/bitnamicharts/ingress-nginx
  ref:
    digest: sha256:a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2
