apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: spegel
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/spegel-org/helm-charts/spegel
  ref:
    tag: "0.6.0"
    digest: sha256:272f4ebc09099d46f493ed32fcbfaaf21c47a447939c976bcae4be1d69101d01