---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: redis
spec:
  interval: 12h
  url: oci://ghcr.io/visualon/bitnamicharts/redis
  ref:
    tag: 23.2.1
    # digest is for pinning, tag is used by renovate
    digest: sha256:82bf7d6d2b36cfcbff26dd85bfeaad37598ccfd8ef8944d3baaa64bc1d30329a
