---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: redis
spec:
  interval: 12h
  url: oci://ghcr.io/visualon/bitnamicharts/redis
  ref:
    tag: 23.0.10
    # digest is for pinning, tag is used by renovate
    digest: sha256:816fff6f5e9e22f34ec98768e95354ee85a825e08bfb75995fcacfbe7224ca83
